baseURL = "kariyach.github.io/index.html"
languageCode = "en-us"
title = "CHIHIRO KARIYA"
theme = "avicenna"
paginate = 5

copyright = "© Copyright notice"

summaryLength = 20

[params]
  subtitle= "Intellectual Historian of Early Modern Ideas"
  mode = "auto" # "dark", "auto", "light"

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "Publications"
url = "/publications"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "Posts"
url = "/"
weight = 4

[markup]
    [markup.tableOfContents]
        endLevel = 2
        ordered = true
        startLevel = 2
  
  [[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/"
  
  [[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"		