---
title: "Publications"
---

:::{.callout-important}
## This is Important

- All papers presented below are written in Japanese.

:::


### Articles \& Chapters
#### James Mackintosh in Bombay: Colonial Rule of the Scottish Enlightenment

> **Abstract**: Neither his contemporaries nor today’s scholarship has paid enough attention to James Mackintosh in Bombay. Mackintosh, a leading figure in the Scottish Enlightenment, was the author of A Discourse on the Study of the Law of Nature and Nations, a book that is forgotten today but that attracted the attention of his contemporaries. He was an exceptional political theorist who stayed in the Indian subcontinent. This study organizes his discussion of state, relations between states, and narrative on civilization and barbarism from the discourse, and discusses how these ideas and narrative were or were not utilized by Mackintosh in Bombay. The essay concludes as follows: He used the idea of state in the rule of law and civil society in Bombay. On the other hand, his theory on the law of nations does not have sufficient concepts and language to discuss empire, such as referring to the protectorate of Great Britain as if it were an independent state. This study argues that he, who had the aporia of legitimacy of acquisition and legitimacy of administration, seems to have wandered into a further aporia, by neglecting to discuss the natives in the subcontinent. The author implies that the colonial application of his Enlightenment thought ̶ especially his conception of political economy ̶ was his own answer to getting out of the aporia.

#### The Eloquence in Wartime: Mackintosh on Burke's Letters on a Regicide Peace

- [https://doi.org/10.34382/00014305](
https://doi.org/10.34382/00014305)

> **Abstract**: This paper explores the political context of eloquence in Britain during the French Revolutionary Wars, by examining the controversy on peace with France. Burke’s enigmatic political pamphlet Letters on a Regicide Peace, published for continuing the war in 1796, is one of the most difficult works to interpret. The pamphlet which interweaves threads of rich rhetoric and antagonism toward France has kept scholarship away for a long time. Some scholars have found in the text international theory, and a newly invented word, diplomacy, emphasizing his talent, originality, and innovation. But since they have not paid attention to the reaction from his contemporary, his intention, and the context, the interpretations may be anachronistic. This essay reads the pamphlet in the contemporary controversy, especially with James Mackintosh, who published Vindiciae Gallicae in 1791. His review on Letters on a Regicide Peace, which appeared in Monthly Review in 1796 and refuted Burke’s opinion, has been rarely considered. This paper argues Mackintosh adapted the alternative strategy focusing on Burke’s eloquence or rhetoric, rule of law, and opinions, which were not any subject to Burke. First, after introducing the period background and brief overview of Letters on a Regicide Peace, it shows that Mackintosh warned Burkes’ eloquence by referring to the canonical speeches by Demosthenes and Cicero, and by putting his pamphlet in the context of literature such as The Life of Henry the Fifth (William Shakespeare) and Paradise Regained (John Milton). Second, it focuses on disagreement on the idea of opinions between them. He locked Burke’s perilous gift for eloquence, which incited people to the war persuasively, and called for anti-war.

#### The International Politics of Jealousy: Edmund Burke, Adam Smith and James Mackintosh

- [https://doi.org/10.51054/sgg.2022.8_51](https://doi.org/10.51054/sgg.2022.8_51)

> **Abstract**: This paper aims to think about global governance through the classics, focusing on the language, in particular on jealousy, of international relations in Britain during the French Revolutionary Wars. This paper explores perceptions on relations between states of the statesman Edmund Burke (1730-1797) and his contemporaries (the political economist (philosopher) Adam Smith (1723-1790) and the political pamphleteer James Mackintosh (1765-1832) . Through the above discussion, it questions what is “classics” in the study of global governance. It is not common to focus on jealousy in the discussion of global governance and inter-state relations. This is partly because jealousy is not a phenomenon or an analytical concept unique to inter-state relations, such as diplomacy, sovereignty (external sovereignty), balance of power theory, or hegemony, and therefore has been avoided from being discussed head-on. But in today's relations between states too, jealousy, far from disappearing, continues to be a source of great trouble.This paper finds that Burke, Smith and Mackintosh commonly perceived that inter-state relations were hampered by jealousy, and they all seem to be pessimistic about overcoming jealousy. What is interesting for this paper, however, is Burke has repeatedly expressed concern that other states or nations were jealous of his state. Adam Smith, in arguing for the 'impartial observer' in his The Theory of Moral Sentiments, emphasis of the importance of lowering passions to the point where others can follow. It is true that we may not be able to overcome jealousy, but by asking ourselves whether our state is not the object of jealousy from other states, we seem to open the way to cooperative governance with other countries.At any given time, classical texts and later generations does not share preconditions. In this respect, the limitations of this paper do not stem solely from global governance. What is important is that we continue to have a sense of learning from the classics, and that we form a common understanding among contemporaries by sharing the classics, or at least sharing the need to do so. Just as the study of international relations has developed primarily through the classicization of international law, global governance seems to need a corresponding classic. Since the study of global governance has a broader scope than the study of international relations, the scope of the classics should be even broader.

### Book Reviews

